# fly.toml app configuration file generated for websocket-game-server-silent-brook-7828 on 2025-07-18T20:00:53+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'websocket-game-server-silent-brook-7828'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
